# Generated by Django 2.2.2 on 2021-10-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Therapists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=25)),
                ('gender', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField(default=25)),
                ('website', models.CharField(max_length=100)),
                ('qual', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=2005)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Person')),
                ('specializations', models.ManyToManyField(to='personal.Specialization')),
            ],
        ),
    ]
