# Generated by Django 2.2.2 on 2021-10-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapists',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
