# Generated by Django 3.2.6 on 2021-10-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='connectionRequest',
            new_name='connectionRequests',
        ),
        migrations.AddField(
            model_name='patient',
            name='connectedTherapist',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
