# Generated by Django 3.2.6 on 2021-10-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='connectedTherapist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.therapist'),
        ),
    ]
