# Generated by Django 3.2.6 on 2021-10-15 12:17

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_patient_connectedtherapist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='connectionRequests',
        ),
        migrations.AddField(
            model_name='patient',
            name='therapistRequests',
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='patient',
            name='connectedTherapist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.therapist'),
        ),
    ]
