# Generated by Django 3.2.6 on 2021-10-15 12:20

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211015_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='connectedTherapist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.therapist'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='therapistRequests',
            field=jsonfield.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
