# Generated by Django 3.2.6 on 2021-10-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211015_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='connectedTherapist',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='therapistRequests',
        ),
        migrations.AddField(
            model_name='patient',
            name='connectionRequests',
            field=models.ManyToManyField(to='main.Therapist'),
        ),
    ]
